# Generated by Django 2.0 on 2018-02-02 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180202_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='tags',
        ),
    ]
