# Generated by Django 2.0 on 2018-02-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_remove_articlemodel_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='tags',
            field=models.ManyToManyField(to='article.TagModel', verbose_name='标签'),
        ),
    ]
