# Generated by Django 2.0 on 2018-02-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20180202_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='摘要'),
        ),
    ]
