# Generated by Django 2.0 on 2018-02-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_articlemodel_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='desc',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='摘要'),
        ),
    ]
