# Generated by Django 2.0 on 2018-02-28 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20180202_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='add_time',
        ),
    ]
