# Generated by Django 2.0 on 2018-02-28 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20180228_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='add_time',
        ),
    ]
