# Generated by Django 2.0 on 2018-02-28 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_auto_20180228_1521'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlineEditorModel',
        ),
    ]
