# Generated by Django 2.0 on 2018-02-28 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_delete_onlineeditormodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='desc',
        ),
    ]
