# Generated by Django 2.0 on 2018-02-28 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_remove_articlemodel_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
